config/routes.rb
Rails.application.routes.draw do
  # 会員用：新規登録とログインのみ
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # 管理者用：ログインのみ
  devise_for :admin, skip: %i[registrations passwords], controllers: {
    sessions: 'admin/sessions'
  }

  # ゲストユーザー用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  # 会員用
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'items/item_search' => 'items#item_search',as: :item_search

    resources :customers, only: %i[show edit update]
    get 'customers/:id/favorites' => 'customers#favorites', as: :favorites
    get 'customers/:id/my_forums' => 'customers#my_forums', as: :my_forums
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: :unsubscribe
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: :withdraw

    resources :recipes do
      resource :favorites, only: %i[create destroy]
      resource :reports, only: %i[create destroy]
      resources :comments, only: %i[create destroy]
      collection do
        get 'search_tag'
        get 'search'
      end
    end

    resource :inquiries, only: %i[new create]
    post 'inquiries/confirm' => 'inquiries#confirm', as: :confirm

    resources :forums do
      resources :forum_comments, only: %i[create destroy]
      resource :attentions, only: %i[create destroy]
      resource :forum_reports, only: %i[create destroy]
    end
  end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    resources :recipes, only: %i[index show destroy] do
      resources :comments, only: [:destroy]
    end
    resources :customers, only: %i[show edit update]
    get 'customers/:id/customer_recipes' => 'customers#customer_recipes', as: :customer_recipes
    resources :tags, only: %i[index create destroy edit update]
    resources :forums, only: %i[index show destroy] do
      resources :forum_comments, only: [:destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :customer
  # cocoon用：親がまだ保存されていない状態で子モデルの中身を保存するためinverse_ofを使用
  has_many :ingredients, inverse_of: :recipe, dependent: :destroy
  has_many :steps, inverse_of: :recipe, dependent: :destroy
  has_many :recipe_tags, dependent: :destroy
  has_many :tags, through: :recipe_tags
  has_many :favorites, dependent: :destroy
  has_many :favorited_customers, through: :favorites, source: :customer
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :reported_customers, through: :reports, source: :customer
  # cocoon用：accepts_nested_attributes_forで親子モデル両方にデータを送信できる
  # cocoon用：allow_destroy: trueで子モデルの削除が可能
  accepts_nested_attributes_for :ingredients
  accepts_nested_attributes_for :steps, allow_destroy: true

  with_options presence: true do
    validates :title, length: { maximum: 15 }
    validates :serving
    validates :description, length: { maximum: 30 }
  end

  has_one_attached :recipe_image

  def get_recipe_image(width, height)
    unless recipe_image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpg')
      recipe_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    recipe_image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def reported_by?(customer)
    reports.exists?(customer_id: customer.id)
  end

  scope :latest, -> { order(created_at: :desc) }

  def self.recipe_favorites
    Recipe.includes(:favorited_customers).sort { |a, b| b.favorited_customers.size <=> a.favorited_customers.size }
  end

  def self.recipe_week_favorites
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    Recipe.includes(:favorited_customers).sort do |a, b|
      b.favorited_customers.includes(:favorites).where(favorites: { created_at: from...to }).size <=>
        a.favorited_customers.includes(:favorites).where(favorites: { created_at: from...to }).size
    end
  end

  def count_favorites_weekly
    favorites.where(favorites: { created_at: (Time.current - 6.day).at_beginning_of_day...Time.current.at_end_of_day }).count
  end

  def self.recipe_reports
    Recipe.includes(:reported_customers).sort { |a, b| b.reported_customers.size <=> a.reported_customers.size }
  end
end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @recipes = if params[:latest]
                # レシピを新着順に並べる
                 Recipe.latest.page(params[:page])
               elsif params[:report]
                # レシピを通報が多い順に並べる
                 Kaminari.paginate_array(Recipe.recipe_reports).page(params[:page])
               else
                 Recipe.page(params[:page])
               end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.ingredients
    @steps = @recipe.steps
    @comments = @recipe.comments.order(created_at: 'DESC').page(params[:page]).per(5)
  end

  def destroy
    recipe = Recipe.find(params[:id])
    redirect_to admin_recipes_path, notice: '投稿を削除しました。' if recipe.destroy
  end

  private

  def post_params
    params.require(:recipe).permit(:report)
  end
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/views/admin/recipes/_admin_recipes.html.erb
<ul class="nav nav-pills mb-2">
  <li class="nav-item">
    <%= link_to "新着順", admin_recipes_path(latest: true) ,class: "nav-link blue-nav mr-2" %>
  </li>
  <li class="nav-item">
    <%= link_to "通報の多い順", admin_recipes_path(report: true) ,class: "nav-link red-nav" %>
  </li>
</ul>
<div class="table-responsive-sm">
  <table class="table table-hover admin-recipes mb-5 mt-2">
    <thead>
      <tr class="admin-table-head">
        <th>タイトル</th>
        <th>ニックネーム</th>
        <th>投稿日</th>
        <th>ステータス</th>
        <th>通報</th>
      </tr>
    </thead>
    <% recipes.each do |recipe| %>
    <tbody>
      <tr>
        <td><%= link_to recipe.title, admin_recipe_path(recipe.id) %></td>
        <td><%= link_to recipe.customer.name, admin_customer_path(recipe.customer.id) %></td>
        <td><%= recipe.created_at.strftime('%Y/%m/%d') %></td>
        <td>
          <% if recipe.customer.is_deleted == false %>
            <p class="text-success font-weight-bold">有効</p>
          <% else %>
            <p class="text-muted font-weight-bold">退会</p>
          <% end %>
        </td>
        <td>
          <!--通報の有無-->
          <% if recipe.reports.ids.empty? %>
            <p class="text-success">問題無し</p>
          <% else %>
            <p class="text-danger">通報数<%= recipe.reports.count %></p>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

app/views/admin/recipes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5 class="midashi2 pl-3 pr-4 mt-5">
        投稿レシピ一覧
      </h5>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto col-md-12 col-lg-12 my-2">
      <%= render"admin/recipes/admin_recipes",recipes: @recipes %>
    </div>
  </div>
  <div class="row my-3">
    <div class="mx-auto"><%= paginate @recipes %></div>
  </div>
</div>

app/views/admin/recipes/show.html.erb
<div class="container">
  <div class="col-lg-offset-2 col-xs-offset-1">
    <div class="row">
      <div class="col">
        <h5 class="midashi2 pl-3 pr-4 my-5">
          <%=@recipe.title%>
        </h5>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-10 col-lg-5 my-3 mx-auto d-flex justify-content-center">
        <%= image_tag @recipe.get_recipe_image(1000,1000),class: "recipe-show-image" %>
      </div>
      <div class="col-xs-12 col-md-10 col-lg-5 pt-lg-3 mx-auto">
        <h5><%= @recipe.description%></h5>
        <span class="text-muted small"><%= @recipe.created_at.strftime('%Y/%m/%d')%></span>
        <p>
          <%= link_to admin_customer_path(@recipe.customer) do%>
          <%= image_tag @recipe.customer.get_customer_image(100,100),class: "recipe-customer-image" %>
          <span class="name-link"><%= @recipe.customer.name%></span>
          <% end %>
        </p>
        <p>
          <%= @recipe.favorites.count %>いいね
        </p>
        <p class="recipe-heading">材料（<%= @recipe.serving %>人前）</p>
        <table class="table table-sm table-borderless">
          <tbody>
            <% @ingredients.each do |ingredient|%>
            <tr class="recipe-table">
              <td><div class="ml-3"><%= ingredient.content%></div></td>
              <td><div class="text-right mr-3"><%= ingredient.quantity%></div></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-lg-1"></div>
    </div>

    <div class="row mt-3">
      <div class="col-xs-12 col-md-10 col-lg-10 mx-auto">
      <p class="recipe-heading">作り方</p>
      <table class="table table-sm table-borderless">
        <tbody>
          <% @steps.each do |step|%>
          <tr class="recipe-table">
            <td><div class="ml-3"><%= step.step_description %></div></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-8 col-md-10 col-xs-12 mx-auto mt-4 mb-2">
        <% @recipe.tags.each do |tag| %>
          <%= link_to search_tag_recipes_path(tag_id: tag.id),class: "tag-button mr-3 px-2" do %>
            <i class="fas fa-tag"></i> <%= tag.name %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="mx-auto col-lg-10 col-md-10 col-12 text-right">
        <%= link_to admin_recipe_path(@recipe),method: :delete,"data-confirm"=>"本当に削除しますか？",class: "btn btn-red my-5" do %>
          <i class="fas fa-trash-alt"></i> レシピ削除
        <% end %>
      </div>
    </div>

    <div class="row mt-5">
      <div class="col-xs-6 col-md-10 col-lg-8 mx-auto">
        <p class="comment-heading">レシピレビュー</p>
        <div id="comment_list">
          <% if @recipe.comments.present? %>
            <%= render"admin/comments/comment_list", comments: @comments %>
          <% else %>
            <p class="ml-2 my-3">レシピレビューはありません</p>
          <% end %>
        </div>
        <div class="row my-3">
          <div class="mx-auto"><%= paginate @comments %></div>
        </div>
      </div>
    </div>
  </div>
</div>