config/routes.rb
Rails.application.routes.draw do
  # 会員用：新規登録とログインのみ
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # 管理者用：ログインのみ
  devise_for :admin, skip: %i[registrations passwords], controllers: {
    sessions: 'admin/sessions'
  }

  # ゲストユーザー用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  # 会員用
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'items/item_search' => 'items#item_search',as: :item_search

    resources :customers, only: %i[show edit update]
    get 'customers/:id/favorites' => 'customers#favorites', as: :favorites
    get 'customers/:id/my_forums' => 'customers#my_forums', as: :my_forums
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: :unsubscribe
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: :withdraw

    resources :recipes do
      resource :favorites, only: %i[create destroy]
      resource :reports, only: %i[create destroy]
      resources :comments, only: %i[create destroy]
      collection do
        get 'search_tag'
        get 'search'
      end
    end

    resource :inquiries, only: %i[new create]
    post 'inquiries/confirm' => 'inquiries#confirm', as: :confirm

    resources :forums do
      resources :forum_comments, only: %i[create destroy]
      resource :attentions, only: %i[create destroy]
      resource :forum_reports, only: %i[create destroy]
    end
  end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    resources :recipes, only: %i[index show destroy] do
      resources :comments, only: [:destroy]
    end
    resources :customers, only: %i[show edit update]
    get 'customers/:id/customer_recipes' => 'customers#customer_recipes', as: :customer_recipes
    resources :tags, only: %i[index create destroy edit update]
    resources :forums, only: %i[index show destroy] do
      resources :forum_comments, only: [:destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :forums, dependent: :destroy
  has_many :attentions, dependent: :destroy
  has_many :forum_comments, dependent: :destroy
  has_many :forum_reports, dependent: :destroy

  validates :name, length: { in: 2..20 }, uniqueness: true

  has_one_attached :customer_image

  def get_customer_image(width, height)
    unless customer_image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpg')
      customer_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    customer_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(name: 'ゲストユーザー', email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = 'ゲストユーザー'
      customer.email = 'guest@example.com'
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id), notice: '登録情報を更新しました。'
    else
      render 'edit'
    end
  end

  def customer_recipes
    @customer = Customer.find(params[:id])
    @recipes = if params[:latest]
                # レシピを新着順に並べる
                 @customer.recipes.order(created_at: 'DESC').page(params[:page])
               elsif params[:report]
                # レシピを通報が多い順に並べる
                 Kaminari.paginate_array(@customer.recipes.recipe_reports).page(params[:page])
               else
                 @customer.recipes.where(customer_id: @customer.id).page(params[:page])
               end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :customer_image, :encrypted_password, :is_deleted)
  end
end

app/controllers/customers/sessions_controller.rb
class Customers::SessionsController < Devise::SessionsController
  def guest_sign_in
    customer = Customer.guest
    sign_in customer
    redirect_to root_path, notice: 'ゲストユーザーでログインしました。'
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/customer_recipes.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5 class="midashi pl-3 pr-4 mt-5">
        <%= @customer.name %>様の投稿
      </h5>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto col-md-12 col-lg-10 my-2">
      <%= link_to "投稿を通報の多い順で表示", admin_customer_recipes_path(report: true) ,class: "btn btn-sm btn-outline-danger my-2" %>
      <%= link_to "投稿すべてを新着順で表示", admin_customer_recipes_path(latest: true) ,class: "btn btn-sm btn-outline-primary my-2" %>
      <div class="row table-responsive-sm">
        <table class="table table-hover admin-recipes mt-2 mx-3">
          <thead>
            <tr>
              <th class="col-6">タイトル</th>
              <th class="col-3">投稿日</th>
              <th class="col-3">通報</th>
            </tr>
          </thead>
          <% @recipes.each do |recipe| %>
            <tbody>
              <tr>
                <td><%=link_to recipe.title, admin_recipe_path(recipe.id) %></td>
                <td><%= recipe.created_at.strftime('%Y/%m/%d') %></td>
                <% if recipe.reports.ids.empty? %>
                  <td class="text-success">問題なし</td>
                <% else %>
                  <td class="text-danger">通報数<%= recipe.reports.count %></td>
                <% end %>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
  <div class="row my-3">
    <div class="mx-auto"><%= paginate @recipes %></div>
  </div>
</div>

app/views/admin/customers/edit.html.erb
<div class="container">
<div class="error-message"><%= render "layouts/error", obj: @customer %></div>
  <div class="row">
    <div class="col">
      <h5 class="midashi2 pl-3 pr-4 mt-5">
        会員情報編集
      </h5>
    </div>
  </div>
  <%= form_with model: @customer,url:admin_customer_path(@customer.id),method: :patch,local: true do |f| %>
  <div class="row">
    <div class="mx-auto col-12 col-md-8 col-lg-5 my-5">
      <tr>
        <td><%= f.file_field:customer_image, accept: "image/*" %></td>
      </tr>
      <tr>
        <td><!--画像のプレビュー-->
          <div id="customer-image-preview">
            <% if @customer.customer_image.attached? %>
              <%= image_tag @customer.get_customer_image(500,500), id: "customer-preview" %>
            <% end %>
           </div>
        </td>
      </tr>
    </div>
    <div class="mx-auto col-12 col-md-8 col-lg-6 pt-lg-5">
      <table class="table table-borderless mt-1 mb-5">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td><%= f.label:ニックネーム %></td>
            <td><%= f.text_field:name, class: "form-control" %></td>
          </tr>
          <tr>
            <td><%= f.label:メールアドレス%></td>
            <td><%= f.email_field:email, class: "form-control" %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <span class="mr-2"><%= f.radio_button :is_deleted, false %>有効</span><%= f.radio_button :is_deleted, true %>退会
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
    <div class="row">
      <div class="text-center col-12 col-md-12 col-lg-12">
        <%= f.submit "変更を保存" ,class: "btn btn-blue mb-5"%>
      </div>
    </div>
  <%end%>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5 class="midashi2 pl-3 pr-4 mt-5">
        会員情報詳細
      </h5>
    </div>
  </div>
  <div class="row">
    <div class="text-center col-12 col-md-5 col-lg-5 mt-5">
      <%= image_tag @customer.get_customer_image(500,500),class: "customer-image" %>
      <h5 class="text-center customer-text"><i class="far fa-user"></i><%= @customer.name %></h5>
    </div>
    <div class="col-12 col-md-7 col-lg-7 my-5 pt-3">
      <table class="table table-borderless mb-5">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>ニックネーム</td>
            <td><%= @customer.name %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <% if @customer.is_deleted == false %>
              <td class="text-success font-weight-bold">有効</td>
            <% else %>
              <td class="text-muted font-weight-bold">退会</td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <div class="mx-auto">
          <%= link_to"編集する",edit_admin_customer_path(@customer.id),class: "btn btn-green mr-5 mt-3" %>
          <%= link_to"レシピ一覧",admin_customer_recipes_path,class: "btn btn-blue mt-3" %>
        </div>
      </div>
    </div>
  </div>
</div>