config/routes.rb
Rails.application.routes.draw do
  # 会員用：新規登録とログインのみ
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # 管理者用：ログインのみ
  devise_for :admin, skip: %i[registrations passwords], controllers: {
    sessions: 'admin/sessions'
  }

  # ゲストユーザー用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  # 会員用
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'items/item_search' => 'items#item_search',as: :item_search

    resources :customers, only: %i[show edit update]
    get 'customers/:id/favorites' => 'customers#favorites', as: :favorites
    get 'customers/:id/my_forums' => 'customers#my_forums', as: :my_forums
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: :unsubscribe
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: :withdraw

    resources :recipes do
      resource :favorites, only: %i[create destroy]
      resource :reports, only: %i[create destroy]
      resources :comments, only: %i[create destroy]
      collection do
        get 'search_tag'
        get 'search'
      end
    end

    resource :inquiries, only: %i[new create]
    post 'inquiries/confirm' => 'inquiries#confirm', as: :confirm

    resources :forums do
      resources :forum_comments, only: %i[create destroy]
      resource :attentions, only: %i[create destroy]
      resource :forum_reports, only: %i[create destroy]
    end
  end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    resources :recipes, only: %i[index show destroy] do
      resources :comments, only: [:destroy]
    end
    resources :customers, only: %i[show edit update]
    get 'customers/:id/customer_recipes' => 'customers#customer_recipes', as: :customer_recipes
    resources :tags, only: %i[index create destroy edit update]
    resources :forums, only: %i[index show destroy] do
      resources :forum_comments, only: [:destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/forum_comment.rb
class ForumComment < ApplicationRecord
  belongs_to :customer
  belongs_to :forum

  validates :forum_comment, presence: true, length: { maximum: 100 }
end

app/controllers/admin/forum_comments_controller.rb
class Admin::ForumCommentsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    @forum = Forum.find(params[:forum_id])
    ForumComment.find(params[:id]).destroy
    @forum_comments = @forum.forum_comments.order(created_at: 'DESC').page(params[:page]).per(5)
  end
end

app/helpers/admin/forum_comments_helper.rb
module Admin::ForumCommentsHelper
end

app/views/admin/forum_comments/_forum_comment_list.html.erb
<% forum_comments.each do |comment| %>
  <table class="table table-borderless">
    <tbody>
      <tr class="row d-flex align-items-center">
        <td class="col-8 col-md-8 col-lg-8"><%= comment.forum_comment %></td>
        <td class="col-2 col-md-3 col-lg-3 text-right">
          <%= link_to admin_customer_path(comment.customer) do %>
            <small>
              <%= image_tag comment.customer.get_customer_image(100,100),class: "comment-customer-image" %>
              <span class="name-link"><%= comment.customer.name %></span>
            </small>
          <% end %>
        </td>
        <td class="col-2 col-md-1 col-lg-1 text-right">
            <%= link_to admin_forum_forum_comment_path(comment.forum, comment), method: :delete,"data-confirm"=>"本当に削除しますか？", remote: true, class: "btn btn-red btn-circle btn-sm m-1" do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/admin/forum_comments/destroy.js.erb
$("#forum_comment_list").html("<%= j(render"admin/forum_comments/forum_comment_list", forum_comments: @forum_comments) %>");
<% if @forum_comments.count <= 0 %>
  $('#forum_comment_list').html('<p class="ml-5 my-5">〜コメントはありません〜</p>')
<% end %>