config/routes.rb
Rails.application.routes.draw do
  # 会員用：新規登録とログインのみ
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # 管理者用：ログインのみ
  devise_for :admin, skip: %i[registrations passwords], controllers: {
    sessions: 'admin/sessions'
  }

  # ゲストユーザー用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  # 会員用
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'items/item_search' => 'items#item_search',as: :item_search

    resources :customers, only: %i[show edit update]
    get 'customers/:id/favorites' => 'customers#favorites', as: :favorites
    get 'customers/:id/my_forums' => 'customers#my_forums', as: :my_forums
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: :unsubscribe
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: :withdraw

    resources :recipes do
      resource :favorites, only: %i[create destroy]
      resource :reports, only: %i[create destroy]
      resources :comments, only: %i[create destroy]
      collection do
        get 'search_tag'
        get 'search'
      end
    end

    resource :inquiries, only: %i[new create]
    post 'inquiries/confirm' => 'inquiries#confirm', as: :confirm

    resources :forums do
      resources :forum_comments, only: %i[create destroy]
      resource :attentions, only: %i[create destroy]
      resource :forum_reports, only: %i[create destroy]
    end
  end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    resources :recipes, only: %i[index show destroy] do
      resources :comments, only: [:destroy]
    end
    resources :customers, only: %i[show edit update]
    get 'customers/:id/customer_recipes' => 'customers#customer_recipes', as: :customer_recipes
    resources :tags, only: %i[index create destroy edit update]
    resources :forums, only: %i[index show destroy] do
      resources :forum_comments, only: [:destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_comment_error.html.erb
<% if obj.errors.any? %>
  <h5>コメントを入力してください</h5>
<% end %>

app/views/layouts/_error.html.erb
<div class="row">
  <div class="col-12 col-lg-6">
    <% if obj.errors.any? %>
      <h3 class="mt-5"><%= obj.errors.count %>個のエラーがあります</h3>
      <ul class="error-list">
        <% obj.errors.full_messages.each do |message| %>
        <div class="error-box px-3 py-1 alert" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">close</span>
          </button>
        <li><%= message %></li>
        </div>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div class="flash">
  <% flash.each do |key, value| %>
  <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col footer-box py-5">
        <div class="footer-text pb-2">
          © 2022 YamaRepi!.Inc /
          <%= link_to item_search_path, class: "rakuten-link" do %><i class="fas fa-bug"></i><% end %>
        </div>
        <div class="inquiry-box">
          <%= link_to(new_inquiries_path,class: "inquiry-link") do %>
            <i class="fas fa-envelope"></i> お問い合わせはこちら
          <% end %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% unless admin_signed_in? %>
  <div class="search mt-3 mr-5"><%= render "layouts/search" ,search: @search%></div>
  <% end %>
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag"yamarepi.png",size: "180x75" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li class="nav-item">
                <%= link_to(customer_path(current_customer.id), class: "nav-link btn btn-rise btn-light mx-3") do %><i class="fas fa-mountain"></i> マイページ<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(recipes_path, class: "nav-link btn btn-rise btn-light mx-3") do %><i class="fas fa-book-open"></i> レシピ一覧<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(new_recipe_path, class: "nav-link btn btn-rise btn-light mx-3") do %><i class="fas fa-utensils"></i> レシピ作成<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(forums_path, class: "nav-link btn btn-rise btn-light mx-3") do %><i class="fas fa-clipboard-list"></i> 掲示板<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(destroy_customer_session_path,method: :delete, class: "nav-link btn btn-rise btn-light mx-3") do %><i class="fas fa-sign-out-alt"></i> ログアウト<% end %>
              </li>
            <%elsif admin_signed_in?%>
              <li class="nav-item">
                <%= link_to(admin_recipes_path, class: "nav-link btn btn-rise btn-light mx-3") do %><i class="fas fa-book-open"></i> レシピ一覧<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(admin_tags_path, class: "nav-link btn btn-rise btn-light mx-3") do %><i class="fas fa-tag"></i> タグ一覧<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(admin_forums_path, class: "nav-link btn btn-rise btn-light mx-3") do %><i class="fas fa-clipboard-list"></i> 掲示板<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(destroy_admin_session_path,method: :delete, class: "nav-link btn btn-rise btn-light mx-3") do %><i class="fas fa-sign-out-alt"></i> ログアウト<% end %>
              </li>
            <%else%>
              <li class="nav-item">
                <%= link_to(about_path, class: "nav-link btn btn-rise btn-light mx-2") do %><i class="fas fa-seedling"></i> About<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(recipes_path, class: "nav-link btn btn-rise btn-light mx-2")do%><i class="fas fa-book-open"></i> レシピ一覧<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(new_customer_registration_path, class: "nav-link btn btn-rise btn-light mx-2") do %><i class="fas fa-user-plus"></i> 新規登録<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(new_customer_session_path, class: "nav-link btn btn-rise btn-light mx-2") do %><i class="fas fa-sign-in-alt"></i> ログイン<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(customers_guest_sign_in_path, method: :post, class: "nav-link btn btn-rise btn-light mx-2") do %><i class="fas fa-user-tie"></i> ゲストログイン(閲覧用)<% end %>
              </li>
            <%end%>
          </ul>
        </div>
    </div>
  </nav>
</header>

app/views/layouts/_loading.html.erb
<div id="loading">
  <div id="loading_box">
    <div class="loading-one animation_loading">
      <p class="loading-text">読み込み中</p>
    </div>
  </div>
</div>

app/views/layouts/_search.html.erb
<%= search_form_for search, url: search_recipes_path do |f| %>
  <%= f.search_field :title_or_ingredients_content_cont, placeholder: "レシピ名・食材名で検索", :required => true, class: "form-contral search-form px-2" %>
  <%= button_tag type: "submit",class: "btn btn-rise btn-search" do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yamarepi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
      <main>
        <%= render 'layouts/flash' %>
        <%= yield %>
        <span id="back">
          <a href="">
            <%= image_tag asset_path('pagetop.png'), data: {"turbolinks"=>false}, class: "pagetop" %>
          </a>
        </span>
      </main>
    <%= render "layouts/footer" %>
  </body>
</html>